#!/bin/bash

## #ddev-generated
## Description: Reset DB container, and fetch a newer one if available.
## Usage: pulldb
## Example: "ddev pulldb"

$HOME/.ddev/bin/docker-compose -f .ddev/.ddev-docker-compose-full.yaml down --rmi all --volumes mtk && ddev restart
