#!/bin/bash

## #ddev-generated
## Description: Container+Volume deletion, then image deletion, then start (db fetch happens at end).
## Usage: pulldb
## Example: "ddev pulldb"

ddev delete --omit-snapshot -y && ddev start
