#!/bin/bash

#ddev-generated
# Support for mtk TablePlus, https://tableplus.com/
# This command is available on macOS only.
## Description: Run TablePlus with mtk database.
## Usage: tableplus
## Example: "ddev tableplus"
## OSTypes: darwin
## HostBinaryExists: /Applications/TablePlus.app,/Applications/Setapp/TablePlus.app

MTK_USERNAME=$(ddev dotenv get .ddev/.env.web --mtk-username)
MTK_PASSWORD=$(ddev dotenv get .ddev/.env.web --mtk-password)
DDEV_MTK_HOST_PORT=$(ddev dotenv get .ddev/.env.web --ddev-mtk-host-port)
MTK_DATABASE=$(ddev dotenv get .ddev/.env.web --mtk-database)
query="mysql://${MTK_USERNAME}:${MTK_PASSWORD}@127.0.0.1:${DDEV_MTK_HOST_PORT:-3206}/${MTK_DATABASE}?Enviroment=local&Name=ddev-${DDEV_SITENAME}"
set -eu -o pipefail

if [ -d "/Applications/Setapp/TablePlus.app" ]; then
    open "$query" -a "/Applications/Setapp/TablePlus.app/Contents/MacOS/TablePlus"
else
    open "$query" -a "/Applications/TablePlus.app/Contents/MacOS/TablePlus"
fi
