#ddev-generated
services:
  mtk:
    # Name of container using standard ddev convention
    container_name: ddev-${DDEV_SITENAME}-mtk
    # See https://mtk.skpr.io/docs/database-image/#build-a-docker-image
    image: ${DDEV_MTK_DOCKER_IMAGE:-mariadb:lts-ubi9}
    # Fetch a fresh DB anytime this image is deleted (thats infrequent). See pulldb command
    pull_policy: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - ${DDEV_MTK_HOST_PORT:-3206}:3306
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - mtk:/var/lib/mysql
volumes:
  mtk:
